services:
  - type: web
    name: disease-predictor
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    workingDirectory: backend
